/* This is a file lists the most depended-upon header files used by
 * the project.  It is automatically generated by:
 *   tools/genCommonHeader -t .35 -p \(Shared/newmat\|Motion/roboop\)/.*
 * When compiling for PLATFORM_LOCAL, this header will be precompiled. 
 * It was created at Thu Sep 21 18:50:36 EDT 2006 and checked into 
 * CVS at $Date: 2006/09/21 23:02:30 $ */

#ifdef __cplusplus //lets us blindly apply to C files as well

#ifdef PLATFORM_LOCAL
#ifdef TGT_ERS210
#include "Shared/attributes.h" //143
#include "Shared/LoadSave.h" //141
#include "Shared/XMLLoadSave.h" //139
#include "Shared/Resource.h" //132
#include "IPC/Thread.h" //131
#include "Shared/get_time.h" //129
#include "Events/EventBase.h" //127
#include "Shared/ReferenceCounter.h" //123
#include "Shared/RobotInfo.h" //118
#include "Shared/CommonInfo.h" //118
#include "Wireless/Socket.h" //117
#include "Shared/ERS210Info.h" //117
#include "Shared/debuget.h" //114
#include "Events/EventListener.h" //108
#include "Behaviors/BehaviorBase.h" //90
#include "Wireless/Wireless.h" //88
#include "Wireless/DummySocket.h" //88
#include "Shared/newmat/newmat.h" //82
#include "Shared/newmat/myexcept.h" //82
#include "Shared/newmat/include.h" //82
#include "Shared/Config.h" //81
#include "IPC/ProcessID.h" //81
#include "Shared/plistBase.h" //80
#include "Shared/Cloneable.h" //80
#include "Shared/plistPrimitives.h" //79
#include "IPC/ListMemBuf.h" //79
#include "Shared/plistCollections.h" //78
#include "IPC/SemaphoreManager.h" //78
#include "IPC/MutexLock.h" //78
#include "Shared/plist.h" //77
#include "Events/EventTrapper.h" //77
#include "Vision/colors.h" //74
#include "IPC/RCRegion.h" //74
#include "Motion/Kinematics.h" //73
#include "Events/EventRouter.h" //73
#include "Shared/ProjectInterface.h" //69
#include "Shared/WorldState.h" //66
#include "Motion/OutputCmd.h" //66
#include "IPC/SharedObject.h" //64
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS210
#ifdef TGT_ERS220
#include "Shared/attributes.h" //143
#include "Shared/LoadSave.h" //141
#include "Shared/XMLLoadSave.h" //139
#include "Shared/Resource.h" //132
#include "IPC/Thread.h" //131
#include "Shared/get_time.h" //129
#include "Events/EventBase.h" //127
#include "Shared/ReferenceCounter.h" //123
#include "Shared/RobotInfo.h" //118
#include "Shared/CommonInfo.h" //118
#include "Wireless/Socket.h" //117
#include "Shared/ERS220Info.h" //117
#include "Shared/debuget.h" //114
#include "Events/EventListener.h" //108
#include "Behaviors/BehaviorBase.h" //90
#include "Wireless/Wireless.h" //88
#include "Wireless/DummySocket.h" //88
#include "Shared/newmat/newmat.h" //82
#include "Shared/newmat/myexcept.h" //82
#include "Shared/newmat/include.h" //82
#include "Shared/Config.h" //81
#include "IPC/ProcessID.h" //81
#include "Shared/plistBase.h" //80
#include "Shared/Cloneable.h" //80
#include "Shared/plistPrimitives.h" //79
#include "IPC/ListMemBuf.h" //79
#include "Shared/plistCollections.h" //78
#include "IPC/SemaphoreManager.h" //78
#include "IPC/MutexLock.h" //78
#include "Shared/plist.h" //77
#include "Events/EventTrapper.h" //77
#include "Vision/colors.h" //74
#include "IPC/RCRegion.h" //74
#include "Motion/Kinematics.h" //73
#include "Events/EventRouter.h" //73
#include "Shared/ProjectInterface.h" //69
#include "Shared/WorldState.h" //66
#include "Motion/OutputCmd.h" //66
#include "IPC/SharedObject.h" //64
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS220
#ifdef TGT_ERS2xx
#include "Shared/attributes.h" //143
#include "Shared/LoadSave.h" //141
#include "Shared/XMLLoadSave.h" //139
#include "Shared/Resource.h" //132
#include "IPC/Thread.h" //131
#include "Shared/get_time.h" //129
#include "Events/EventBase.h" //127
#include "Shared/ReferenceCounter.h" //123
#include "Shared/RobotInfo.h" //118
#include "Shared/CommonInfo.h" //118
#include "Wireless/Socket.h" //117
#include "Shared/ERS2xxInfo.h" //117
#include "Shared/debuget.h" //114
#include "Events/EventListener.h" //108
#include "Behaviors/BehaviorBase.h" //90
#include "Wireless/Wireless.h" //88
#include "Wireless/DummySocket.h" //88
#include "Shared/newmat/newmat.h" //82
#include "Shared/newmat/myexcept.h" //82
#include "Shared/newmat/include.h" //82
#include "Shared/Config.h" //81
#include "IPC/ProcessID.h" //81
#include "Shared/plistBase.h" //80
#include "Shared/Cloneable.h" //80
#include "Shared/plistPrimitives.h" //79
#include "IPC/ListMemBuf.h" //79
#include "Shared/plistCollections.h" //78
#include "IPC/SemaphoreManager.h" //78
#include "IPC/MutexLock.h" //78
#include "Shared/plist.h" //77
#include "Events/EventTrapper.h" //77
#include "Vision/colors.h" //74
#include "IPC/RCRegion.h" //74
#include "Motion/Kinematics.h" //73
#include "Events/EventRouter.h" //73
#include "Shared/ProjectInterface.h" //69
#include "Shared/WorldState.h" //66
#include "Motion/OutputCmd.h" //66
#include "IPC/SharedObject.h" //64
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS2xx
#ifdef TGT_ERS7
#include "Shared/attributes.h" //144
#include "Shared/LoadSave.h" //142
#include "Shared/XMLLoadSave.h" //140
#include "Shared/Resource.h" //132
#include "IPC/Thread.h" //131
#include "Shared/get_time.h" //130
#include "Events/EventBase.h" //128
#include "Shared/ReferenceCounter.h" //124
#include "Shared/RobotInfo.h" //118
#include "Shared/ERS7Info.h" //118
#include "Shared/CommonInfo.h" //118
#include "Wireless/Socket.h" //117
#include "Shared/debuget.h" //115
#include "Events/EventListener.h" //109
#include "Behaviors/BehaviorBase.h" //91
#include "Wireless/Wireless.h" //88
#include "Wireless/DummySocket.h" //88
#include "Shared/newmat/newmat.h" //83
#include "Shared/newmat/myexcept.h" //83
#include "Shared/newmat/include.h" //83
#include "Shared/Config.h" //81
#include "IPC/ProcessID.h" //81
#include "Shared/plistBase.h" //80
#include "Shared/Cloneable.h" //80
#include "Shared/plistPrimitives.h" //79
#include "IPC/ListMemBuf.h" //79
#include "Shared/plistCollections.h" //78
#include "IPC/SemaphoreManager.h" //78
#include "IPC/MutexLock.h" //78
#include "Events/EventTrapper.h" //78
#include "Shared/plist.h" //77
#include "Vision/colors.h" //74
#include "IPC/RCRegion.h" //74
#include "Events/EventRouter.h" //74
#include "Motion/Kinematics.h" //73
#include "Shared/ProjectInterface.h" //69
#include "Shared/WorldState.h" //66
#include "Motion/OutputCmd.h" //66
#include "IPC/SharedObject.h" //64
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS7
#endif //PLATFORM_LOCAL

#ifdef PLATFORM_APERIOS
#ifdef TGT_ERS210
#include "Shared/attributes.h" //127
#include "Shared/LoadSave.h" //126
#include "Shared/XMLLoadSave.h" //125
#include "Shared/get_time.h" //121
#include "Events/EventBase.h" //120
#include "Shared/CommonInfo.h" //115
#include "Shared/RobotInfo.h" //114
#include "Shared/ERS210Info.h" //114
#include "Wireless/Socket.h" //111
#include "Shared/debuget.h" //101
#include "Events/EventListener.h" //99
#include "Shared/ReferenceCounter.h" //86
#include "Behaviors/BehaviorBase.h" //84
#include "Wireless/Wireless.h" //83
#include "Wireless/DummySocket.h" //83
#include "Shared/Config.h" //80
#include "Shared/newmat/newmat.h" //79
#include "Shared/newmat/myexcept.h" //79
#include "Shared/newmat/include.h" //79
#include "Motion/Kinematics.h" //71
#include "Shared/StackTrace.h" //70
#include "IPC/ProcessID.h" //69
#include "Events/EventTrapper.h" //68
#include "Events/EventRouter.h" //67
#include "Shared/Resource.h" //65
#include "Shared/WorldState.h" //64
#include "Vision/colors.h" //63
#include "Motion/OutputCmd.h" //63
#include "IPC/MutexLock.h" //63
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS210
#ifdef TGT_ERS220
#include "Shared/attributes.h" //127
#include "Shared/LoadSave.h" //126
#include "Shared/XMLLoadSave.h" //125
#include "Shared/get_time.h" //121
#include "Events/EventBase.h" //120
#include "Shared/CommonInfo.h" //115
#include "Shared/RobotInfo.h" //114
#include "Shared/ERS220Info.h" //114
#include "Wireless/Socket.h" //111
#include "Shared/debuget.h" //101
#include "Events/EventListener.h" //99
#include "Shared/ReferenceCounter.h" //86
#include "Behaviors/BehaviorBase.h" //84
#include "Wireless/Wireless.h" //83
#include "Wireless/DummySocket.h" //83
#include "Shared/Config.h" //80
#include "Shared/newmat/newmat.h" //79
#include "Shared/newmat/myexcept.h" //79
#include "Shared/newmat/include.h" //79
#include "Motion/Kinematics.h" //71
#include "Shared/StackTrace.h" //70
#include "IPC/ProcessID.h" //69
#include "Events/EventTrapper.h" //68
#include "Events/EventRouter.h" //67
#include "Shared/Resource.h" //65
#include "Shared/WorldState.h" //64
#include "Vision/colors.h" //63
#include "Motion/OutputCmd.h" //63
#include "IPC/MutexLock.h" //63
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS220
#ifdef TGT_ERS2xx
#include "Shared/attributes.h" //127
#include "Shared/LoadSave.h" //126
#include "Shared/XMLLoadSave.h" //125
#include "Shared/get_time.h" //121
#include "Events/EventBase.h" //120
#include "Shared/CommonInfo.h" //115
#include "Shared/RobotInfo.h" //114
#include "Shared/ERS2xxInfo.h" //114
#include "Wireless/Socket.h" //111
#include "Shared/debuget.h" //101
#include "Events/EventListener.h" //99
#include "Shared/ReferenceCounter.h" //86
#include "Behaviors/BehaviorBase.h" //84
#include "Wireless/Wireless.h" //83
#include "Wireless/DummySocket.h" //83
#include "Shared/Config.h" //80
#include "Shared/newmat/newmat.h" //79
#include "Shared/newmat/myexcept.h" //79
#include "Shared/newmat/include.h" //79
#include "Motion/Kinematics.h" //71
#include "Shared/StackTrace.h" //70
#include "IPC/ProcessID.h" //69
#include "Events/EventTrapper.h" //68
#include "Events/EventRouter.h" //67
#include "Shared/Resource.h" //65
#include "Shared/WorldState.h" //64
#include "Vision/colors.h" //63
#include "Motion/OutputCmd.h" //63
#include "IPC/MutexLock.h" //63
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS2xx
#ifdef TGT_ERS7
#include "Shared/attributes.h" //127
#include "Shared/LoadSave.h" //126
#include "Shared/XMLLoadSave.h" //125
#include "Shared/get_time.h" //121
#include "Events/EventBase.h" //120
#include "Shared/ERS7Info.h" //115
#include "Shared/CommonInfo.h" //115
#include "Shared/RobotInfo.h" //114
#include "Wireless/Socket.h" //111
#include "Shared/debuget.h" //101
#include "Events/EventListener.h" //99
#include "Shared/ReferenceCounter.h" //86
#include "Behaviors/BehaviorBase.h" //84
#include "Wireless/Wireless.h" //83
#include "Wireless/DummySocket.h" //83
#include "Shared/Config.h" //80
#include "Shared/newmat/newmat.h" //79
#include "Shared/newmat/myexcept.h" //79
#include "Shared/newmat/include.h" //79
#include "Motion/Kinematics.h" //71
#include "Shared/StackTrace.h" //70
#include "IPC/ProcessID.h" //69
#include "Events/EventTrapper.h" //68
#include "Events/EventRouter.h" //67
#include "Shared/Resource.h" //65
#include "Shared/WorldState.h" //64
#include "Vision/colors.h" //63
#include "Motion/OutputCmd.h" //63
#include "IPC/MutexLock.h" //63
#include "Shared/newmat/newmatio.h" //forced (pattern match)
#include "Shared/newmat/newmatap.h" //forced (pattern match)
#include "Motion/roboop/utils.h" //forced (pattern match)
#include "Motion/roboop/robot.h" //forced (pattern match)
#include "Motion/roboop/config.h" //forced (pattern match)
#endif //TGT_ERS7
#endif //PLATFORM_APERIOS

#endif //cplusplus
