#!/bin/sh

cd "`dirname \"$0\"`"
if [ ! -r org/tekkotsu/mon/ControllerGUI.java ] ; then
	echo "Cannot access org/tekkotsu/mon/ControllerGUI.java"
	echo "Make sure this script is located at the root of the java package tree"
	echo "(i.e. Tekkotsu/tools/mon)"
	exit 1;
fi;

if [ ! -r org/tekkotsu/mon/ControllerGUI.class ] ; then
	echo "Cannot access Java executable."
	echo "Perhaps the tools need to be compiled.  Go to the Tekkotsu/tools"
	echo "directory and type 'make'"
	exit 1;
fi;

if [ "`uname`" = "Darwin" ] ; then
	JAVAFLAGS="${JAVAFLAGS} -Xdock:name=ControllerGUI -Xdock:icon=images/ControllerIcon.png"
fi

java ${JAVAFLAGS} -Xmx256M org.tekkotsu.mon.ControllerGUI $* &

